# Generated by Django 5.0.1 on 2024-01-07 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('recetario', '0008_alimento2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionUsuarioComida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetario.alimento2')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='comidas_relacionadas',
            field=models.ManyToManyField(related_name='usuarios_relacionados', to='Account.relacionusuariocomida'),
        ),
    ]
