# Generated by Django 5.0.1 on 2024-01-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigomex2', models.IntegerField()),
                ('nombre_del_alimento', models.CharField(max_length=255)),
                ('energ_kcal', models.FloatField()),
                ('carbohydrt', models.FloatField()),
                ('lipid_tot', models.FloatField()),
                ('protein', models.FloatField()),
                ('fiber_td', models.FloatField()),
                ('calcium', models.FloatField()),
                ('iron', models.FloatField()),
                ('ironhem', models.FloatField()),
                ('ironnohem', models.FloatField()),
                ('zinc', models.FloatField()),
                ('vit_c', models.FloatField()),
                ('thiamin', models.FloatField()),
                ('riboflavin', models.FloatField()),
                ('niacin', models.FloatField()),
                ('panto_acid', models.FloatField()),
                ('vit_b6', models.FloatField()),
                ('folic_acid', models.FloatField()),
                ('food_folate', models.FloatField()),
                ('folate_dfe', models.FloatField()),
                ('vit_b12', models.FloatField()),
                ('vit_a_rae', models.FloatField()),
                ('vit_e', models.FloatField()),
                ('vit_d_iu', models.FloatField()),
                ('vit_k', models.FloatField()),
                ('fa_sat', models.FloatField()),
                ('fa_mono', models.FloatField()),
                ('fa_poly', models.FloatField()),
                ('chole', models.FloatField()),
            ],
        ),
    ]
