# Generated by Django 5.0.1 on 2024-01-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='chole',
            field=models.IntegerField(),
        ),
    ]
