# Generated by Django 5.0.1 on 2024-01-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0002_alter_alimento_chole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='id',
        ),
        migrations.AlterField(
            model_name='alimento',
            name='chole',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='codigomex2',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
