# Generated by Django 5.0.1 on 2024-01-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0004_alimento1_alter_alimento_chole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
