# Generated by Django 5.0.1 on 2024-01-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0005_alter_alimento1_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
