# Generated by Django 5.0.1 on 2024-01-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0007_alter_alimento1_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigomex2', models.IntegerField()),
                ('nombre_del_alimento', models.CharField(max_length=255)),
                ('energ_kcal', models.FloatField()),
                ('carbohydrt', models.FloatField()),
                ('lipid_tot', models.FloatField()),
                ('protein', models.FloatField()),
            ],
        ),
    ]
